#Adding to address this bug https://access.redhat.com/solutions/6012601
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-workaround993-rolebinding
  namespace: sealed-secrets
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
roleRef:
  kind: Role 
  name: argocd-workaround993-role
  apiGroup: rbac.authorization.k8s.io
