apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sealed-secrets-operator-helm
  namespace: sealed-secret
spec:
  channel: alpha
  name: sealed-secrets-operator-helm
  source: sealed-secrets-catalog
  sourceNamespace: openshift-marketplace
