#Adding to address this bug https://access.redhat.com/solutions/6012601
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-workaround993-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]