kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testflask-cicd-pvc
  namespace: testflask-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
