resources:
  - appdev-environment.yaml
  - appdev-rolebinding.yaml
  - mysql-secret.yaml
  - workaround-role.yaml
  - workaround-rolebinding.yaml
  - workaround-rolebinding-sa2.yaml
namespace: appdev
