resources:
  - testFlask-argo-app.yaml
  - testFlask-cicd-app.yaml
  - appdev-env.yaml
  - appprod-env.yaml
  - appprod-app-testflask.yaml
# To edit Branch change value in below file.
transformers:
  - ./transformers/add-branch.yaml
