apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: gitops-webhook-event-listener-route
  namespace: testflask-cicd
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-testflask-listener
    weight: 100
  wildcardPolicy: None
