kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/connects-to: mysql
  name: testflask
  labels:
    app: testflask
    app.kubernetes.io/part-of: testflask
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - testflask
        from:
          kind: ImageStreamTag
          name: "testflask:latest"
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: testflask
    deployment: testflask
  template:
    metadata:
      labels:
        app: testflask
        deploymentconfig: testflask
    spec:
      containers:
        - name: testflask
          image: testflask:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_CONFIG
              value: gunicorn.conf.py
            - name: APP_MODULE
              value: "testapp:app"
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MYSQL_USER
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
